language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --dev --no-interaction
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=psr2 ./src
  - ./vendor/bin/phpmd src/ text phpmd.xml.dist
