<?php /* @var $collector \DoctrineORMModule\Collector\MappingCollector */ ?>
<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3gkVFDExApseBwAAAUNJREFUOMut1TFrFGEQxvHfe77Re8E22GhnYx3BLo0fQNOd2lnbB8Fe0geCCJaiWIgfwMZKSGFnmUbBQqwURnOXuzSzsIXF3W4Glh0W3v8+M8/sbIkI2MIl4+IM85qwJ9jFfCBsC59wWFPZLu4bH0c1kyVOcIwVZgNgc5j0JL9trc1aaw/GSJykot94GhGriFjh75rXv6yuU7iqmRyg4Xrm8w3M2Mf37lxNlTewjau4hcWawJpntpPxtUTEFG9wb6TDHzDrTDm9gJE57bs8xfPWWmmtlTHU2ssfRcTNbPSQuNwBF3iBZ7iN1/iMsqagh/iFl1jUnKNv+JGf4ZcNx+YPfiZjWSLiCl7lm5bdgK4JLAmdZGWPa+9h3+3pwI1TJr2Gvsfe2Hmsvfs17GxQ7v8UqrlpP+Iu7mQL3g1csGflon8B52+SX25xRYdUAAAAAElFTkSuQmCC" alt="Environment">
        <span class="zdt-toolbar-info">
            Environment
        </span>
    </div>
    <div class="zdt-toolbar-detail">
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-label">Environment</span>
            <span class="zdt-detail-value"><?php echo $this->collector->getEnvironment(); ?></span>
        </span>
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-label">Timezone</span>
            <span class="zdt-detail-value"><?php echo $this->collector->getTimezone(); ?></span>
        </span>
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-label">Locale</span>
            <span class="zdt-detail-value"><?php echo $this->collector->getLocale(); ?></span>
        </span>
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-label">PHP extensions</span>
            <span class="zdt-detail-value">
                <pre><?php echo implode("\n", $this->collector->getPhpExtensions()) ?></pre>
            </span>
        </span>
    </div>
</div>
