<?php /* @var $collector \DoctrineORMModule\Collector\MappingCollector */ ?>
<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAalAAAGpQEXmZfdAAAAB3RJTUUH3gkVFC8CaQpAzgAAAXxJREFUSMftlTFLHUEURo/DEpJGUAiiIGhjeIJVQKuA/gWxDanTCFb2NinshEBAS8FC0kqa/AIRUqR4VUqxEjSJWuTctRnD8nj7dl9UsMjAZZed2fPN7L3f3ZGyLHnMkXjk8TQFImIjIsZbLS7LslWoz9RldUct1a/qmjo+6L228HX1Zwb3huq+Ojq0gDqmHtWAe+OH+rqXMTKoTCPiM7A6RHpOgYWU0nljkiPi3ZBwgClgt/qg9gQR0QVe/WN1dlJK3doTRMTkPeAAK7WfKCJmgPf39NdqRCwCFH0mC6ADXAKjAyDnwHG+nwXmgG/AGVACk32Nlg31qaEku+pyXv9W/aUeqkWtD9SX6pvs0H7QQ7WjTuf1L9S9ylxRazR1Qv2uXqlb6u8akQv1LMdFE7wqsF2BXKkf8rXJvQPhf50cEQVwAKzlpN0AH4F5YBu47tcngZOU0p9W3VQt8o7udnetLrXttq26aY/IF/X5gwpURDYfAt7YTf//9AFuAXdXVidgrs7dAAAAAElFTkSuQmCC" alt="Request">
        <span class="zdt-toolbar-info">
            Request
        </span>
    </div>
    <div class="zdt-toolbar-detail">
        <?php
        $collectors = array(
            'Get'    => $this->collector->getGet(),
            'Post'   => $this->collector->getPost(),
            'Cookie' => $this->collector->getCookie(),
            'File'   => $this->collector->getFile(),
        );

        foreach ($collectors as $collector => $collection) {
            if ($collection) { ?>
            <span class="zdt-toolbar-info">
                <span class="zdt-detail-label"><?php echo $collector ?></span>
                    <span class="zdt-detail-value">
                    <pre><?php
                    foreach ($collection as $key => $val) {
                        echo $key . ': ' . $val . "\n";
                    }
                    ?>
                    </pre>
                </span>
            </span>
            <?php
            }
        }
        ?>
    </div>
</div>
